stages:
  - build
  - test

### Secret management

# Don't allow reading secret-containing files so that we won't leak secrets
# into build outputs.
#
# We use files instead of environment variables to pass secrets - otherwise
# the trick would not work.
#
# NOTE: other jobs may not use "before_script" because it will override the
# "before_script" we define here.
default:
  before_script:
    # All SECRET_* variables point to files containing secrets; make them
    # unreadable.
    - for var in $(env | awk -F= '{if($1 ~ /SECRET_/) print $1}'); do
        ( eval filename=\$$var;
          chmod 0 $filename; )
      done

    # get_secret loads secret X from the SECRET_X file.
    - get_secret() {
        eval local filename=\$SECRET_$1;
        chmod 400 $filename;
        export $1="$(cat $filename)";
        chmod 0 $filename;
      }

### Build

# Build the Fencer Docker image
compile:
  stage: build
  image: nixos/nix
  script:
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - cachix use fencer
    - imagepath=$(nix-build docker.nix)
    - nix-store -qR --include-outputs $(nix-instantiate docker.nix)
        | ( get_secret CACHIX_SIGNING_KEY;
            cachix push fencer )
    - cp $imagepath fencer.tar.gz
  artifacts:
    paths:
      - fencer.tar.gz

# Build the Go integration test
compile_integration:
  stage: build
  image: nixos/nix
  script:
    - imagepath=$(nix-build test_integration_go/docker.nix)
    - cp $imagepath test_integration_go.tar.gz
  artifacts:
    paths:
      - test_integration_go.tar.gz

### Test

integration:
  stage: test
  image: docker:19.03.0
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.0-dind
  script:
    # Create a Docker network for the containers
    - docker network create test

    # Run Fencer
    - docker load -i fencer.tar.gz
    - docker run
        -v $(pwd)/test_integration_go/config:/srv/runtime_data/current
        -e RUNTIME_SUBDIRECTORY=ratelimit
        -p 50051:50051
        --name fencer
        --network test
        --detach
        juspay/fencer
    - sleep 5

    # Run the test
    - docker load -i test_integration_go.tar.gz
    - docker run
        -e GRPC_HOST=fencer
        --network test
        test_integration_go
