stages:
  - build
  - test
  - gencode
  - release

### Build

# Build the Fencer Docker image
compile:
  stage: build
  image: nixos/nix
  environment:
    # GitLab provides the Cachix signing key to all jobs tagged with
    # 'compile' (i.e. only this job)
    name: compile
  script:
    # Build the Docker image and create a list of paths to push to Cachix.
    # The secret signing key should not be available to the build process.
    - ( unset CACHIX_SIGNING_KEY;
        nix-env -iA cachix -f https://cachix.org/api/v1/install;
        cachix use fencer;
        imagepath=$(nix-build docker.nix);
        cp $imagepath fencer.tar.gz;
        nix-store -qR --include-outputs $(nix-instantiate docker.nix) > paths
      )
    # Push built paths to Cachix
    - cachix push fencer < paths
  artifacts:
    paths:
      - fencer.tar.gz

# Build the Go integration test
compile_integration:
  stage: build
  image: nixos/nix
  script:
    - imagepath=$(nix-build test_integration_go/docker.nix)
    - cp $imagepath test_integration_go.tar.gz
  artifacts:
    paths:
      - test_integration_go.tar.gz

### Test

integration:
  stage: test
  image: docker:19.03.0
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
  script:
    # Create a Docker network for the containers
    - docker network create test

    # Run Fencer

    # A pipeline would report that a container named "fencer" already
    # exists (possibly from a job for a different pull request) so
    # choosing a random container name deals with this
    # issue. Furthermore, using a named constant helps with informing
    # where this name is used (compared to "fencer" which has an
    # overloaded meaning in the CI).
    - CNAME="fencer-"$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 25 ; echo '')
    - docker load -i fencer.tar.gz
    - docker run
        -v $(pwd)/test_integration_go/config:/srv/runtime_data/current
        -e RUNTIME_SUBDIRECTORY=ratelimit
        --name $CNAME
        --network test
        --detach
        juspay/fencer
    - sleep 5

    # Run the test
    - docker load -i test_integration_go.tar.gz
    - docker run
        -e GRPC_HOST=$CNAME
        --network test
        test_integration_go

### Checking checked-in generated code is up to date

outofdate:
  stage: gencode
  image: nixos/nix
  script:
    - nix-shell --run ./bin/protoGen.sh

### Release

release_docker:
  stage: release
  image: docker:19.03.0
  environment:
    # GitLab provides the GitHub access token to all jobs tagged with
    # 'release_docker' (i.e. only this job)
    name: release_docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.0-dind
  script:
    - echo "$GITHUB_ACCESS_TOKEN"
        | docker login docker.pkg.github.com --username juspay --password-stdin
    - docker load -i fencer.tar.gz
    - docker tag juspay/fencer docker.pkg.github.com/juspay/fencer/fencer:master
    - docker push docker.pkg.github.com/juspay/fencer/fencer:master
  only:
    - master
