language: nix
os: linux
dist: bionic

stages:
  - build
  - test
  - gen-code
  - release

jobs:
  include:

    # Build the Fencer Docker image
    - stage: build
      script:
        # Build the Docker image and create a list of paths to push to Cachix.
        # The secret signing key should not be available to the build process.
        - ( unset CACHIX_SIGNING_KEY;
            nix-env -iA cachix -f https://cachix.org/api/v1/install;
            cachix use fencer;
            imagepath=$(nix-build docker.nix);
            cp $imagepath fencer.tar.gz;
            nix-store -qR --include-outputs $(nix-instantiate docker.nix) > paths
          )
        # Push built paths to Cachix
        - cachix push fencer < paths
      workspaces:
        create:
          name: build-docker
          paths:
            - fencer.tar.gz
      env:
        # CACHIX_SIGNING_KEY
        - secure: "vNNLfNScRuluP7zmlkCv/9uD+haHZ+iNv5FmWbXA757roaUgXBwRHZptM7wkUCUnhWVKiY9TRBJlCg5NAfNtUB1ElDZifLeVnUzaAsF4y7HP/hDYGmg+NnCB4EhBtc8vmATYK323VKzHCGiApKO0EvO7Oc8CRhrk/RFjVA6JoXYn8rM9FXcvT2AAXGzZmbevH5uUSlY61qmCF0YJdQdtjrwzDk1P/NQCKppxOHlJs1j38BF7ax94gKq2sCMXQA3d4V47WxKZgSvG+fBdXeFAwDs+avnTQ9hTFOb08yeCkIfUlx/GzSH6AVZR2tOwg59MVf9rTDIAExe3slNdDnicwWR1iV1ffmeYzztxA/359/YSYbL06ux0Mq8WsC2wg6+QlIo/K7Lc2q9J8Eye3zwfMGPkSNFUQuSkq+dCdN2r3xT3t6qfhdXo90f7GGvSmBwGc63Cao4rPBc7I98q9SLC4OjSXG4ktgqV6zzGG29/Y+sdpq0WN2pcHB2676WF+jyXrmEgm7Fq2SDU2wdxjA3ZviSbw8gUFvF1/tG/O42juYGMjztBg+eLBf+ZcehsFLctu8tRtMn6PouPfd5OwYmG4IsVBLyNa8lK9I/Hl5RGX5X2RWfCbZz98yzvoAU3T+GgDzQ4apODVnquIX0ebQDhM8s+3Av/+pWnqe5fq3iYtbU="

    # Build the Go integration test
    - stage: build
      script:
        - imagepath=$(nix-build test_integration_go/docker.nix)
        - cp $imagepath test_integration_go.tar.gz
      workspaces:
        create:
          name: build-test
          paths:
            - test_integration_go.tar.gz

    # Run integration tests
    - stage: test
      services:
        - docker
      workspaces:
        use:
          - build-docker
          - build-test
      script:
        # Create a Docker network for the containers
        - docker network create test
        # Run Fencer
        - docker load -i fencer.tar.gz
        - docker run
            -v $(pwd)/test_integration_go/config:/srv/runtime_data/current
            -e RUNTIME_SUBDIRECTORY=ratelimit
            --name fencer-server
            --network test
            --detach
            juspayin/fencer
        - sleep 5
        # Run the test
        - docker load -i test_integration_go.tar.gz
        - docker run
            -e GRPC_HOST=fencer-server
            --network test
            test_integration_go

    ### Checking checked-in generated code is up to date
    - stage: gen-code
      script:
        - nix-env -iA cachix -iA git -f https://cachix.org/api/v1/install
        - cachix use fencer
        - nix-shell --run ./scripts/protoGen.sh
        - DIFF=$(git diff lib/Fencer/Proto.hs | wc -c)
        - if [ "$DIFF" != "0" ]; then exit 1; fi

    ### Release
    - stage: release
      services:
        - docker
      env:
        # DOCKERHUB_ACCESS_TOKEN
        - secure: "cLVBcS5xFdhPGFH17xI5Au+Ui3LpcgDjJT/XTC5sGFf/UKkhB1UfyodxXvzxLuRYR3fAaoETAV8gB5wZ/nwVsJ4oAWzu2wvrBp/ORvwF77zyIro/S4ZnTev3gDkaU8We52MG+Yc3mUAXClz/pock7d5RKMYBony8mHB29iHohe7DNFvNHogMiLgjajX8DHUIPwroBsL3DGSFIFaCkw+dkv5vSRWa69vCMpQl0uDaB+2vm+mKIs8RA01eePOL+tlyLnkwhM7zf8Km+Bqkh5SbHNopnREFAcVdX6OU9dfGb9iY6ZasVU/tQbNVHeUPQTirhL6ICYLPWuCiKqBEHMLDj7WgbXoUvqCgE95723RGff5XUjsR/SgCntB/MEj48adylKDdibm4qV6iqtKvT4NpXCbQLORg+bRtgG+8klP/ZMYTYUTnMHikO+kP6Dz3Lm8QVDSeCn+WdseeQMIsfkjBwdkKi51l5nXP/ObktjiqFiT51UX3ieER88JtAZKgd2Hbc4LrjvvrMHLWiNTG/BghVQl/1/ls/3p5BXF8O/VJO++3f6bZ1kSlAZ4ik0uxoSajEHt1vkVU2S8OdTOPvVv/XG40RZfnVTX0mOw+2VsLLJ03smoWw2wkPl1T/DvrCjvRVnHDD3t3AX/0z2zIJ2jkaTgxC/wi5Ocp2U7BA2usW74="
      workspaces:
        use:
          - build-docker
      script:
        - echo "$DOCKERHUB_ACCESS_TOKEN" | docker login --username juspayin --password-stdin
        - docker load -i fencer.tar.gz
        # Tag the image with commit hash and push
        - HASH=$(git log -1 --pretty=%h)
        - docker tag juspayin/fencer "juspayin/fencer:$HASH"
        - docker push "juspayin/fencer:$HASH"
        # Tag the same image with "master" and push
        # - docker tag juspayin/fencer "juspayin/fencer:master"
        # - docker push "juspayin/fencer:master"
      if: type = push
